### ISSUE TITLE
VAT discount is not applied on shipment fees

### ISSUE THREAD

**Issue by adrian3d** [gewebe/SyliusVATPlugin#2]
Hi, 

I implemented you package in one of my project. The client asked for removing the vat on the order, shipment fees included. I was surprised that the plugin does not take that in charge.

Do you plan to implement that ? I can create a PR to help you if you want.

**Comment by gewebe** [comment]
Hello @adrian3d,

thanks for reporting this issue. You're right, the tax should not apply to the shipping fees either.

It would be great to reproduce this behavior and extend the [tax total checkout](https://github.com/gewebe/SyliusVATPlugin/blob/master/features/checkout/seeing_tax_total_dependent_on_country_and_vat.feature) test or create a similar one before implementing this feature. 

I'll be happy if you can create a PR, otherwise I'll do it as soon as possible.

**Comment by gewebe** [comment]
@adrian3d now you can update to package version v1.2.3 and VAT will be correctly deducted from the shipping fees

**Comment by adrian3d** [comment]
Thanks man !

**Comment by adrian3d** [comment]
Thanks dude !
